### PR TITLE
Move nicelog script out of keepalived task

### PR DESCRIPTION
**Pull request by meisterT**
It is not related to this, move it to common domserver tasks.

### CODE REVIEW

**Comment by vmcj** [comment]
> It is not related to this, move it to common domserver tasks.

I miss the part where it was in keepalived.

**Comment by meisterT** [comment]
> > It is not related to this, move it to common domserver tasks.
> 
> I miss the part where it was in keepalived.

Did you see that the file was moved?

**Comment by vmcj** [comment]
> > > It is not related to this, move it to common domserver tasks.
> > 
> > 
> > I miss the part where it was in keepalived.
> 
> Did you see that the file was moved?

I meant in the keepalived role, but it seems we copied with a wildcard there.

**Comment by meisterT** [comment]
@vmcj do you want to see any additional changes?

**Review by vmcj — APPROVED** [review]

**Pull request merged**
